### ISSUE TITLE
pcap commonly truncated

### ISSUE THREAD

**Issue by mcmanus** [mozilla/stoneridge#8]
pcaps are a great and fundamental feaure.. unfortunately in my first set of 4 of them were all truncated.. the windows one was short, and the 3 mac ones were empty. nick says the linux ones are better.

**Comment by nwgh** [comment]
I pushed an update yesterday that appears to have fixed this (a random sampling of pcaps from mac and windows clients since the update all have the relevant information), so I'm going to close this one out.

**Comment by nwgh** [comment]
I should note, the update was _designed_ to fix this, so it's not like a surprise "hey, that fixed it! I wonder why?" kind of thing :-)
